# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('header', models.CharField(max_length=256, verbose_name='Header')),
                ('keywords', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Keywords')),
                ('description', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Description')),
                ('url', models.CharField(max_length=256, verbose_name='URL')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='Intro')),
                ('outro', models.TextField(blank=True, null=True, verbose_name='Outro')),
                ('head_code', models.TextField(blank=True, null=True, verbose_name='Head Code')),
                ('footer_code', models.TextField(blank=True, null=True, verbose_name='Footer Code')),
                ('public', models.BooleanField(default=True, verbose_name='Public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='sites.Site', verbose_name='Site')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Meta Data',
                'verbose_name_plural': 'Meta Data',
            },
        ),
        migrations.CreateModel(
            name='ExtraSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('key', models.CharField(max_length=128, verbose_name='Key')),
                ('type', models.CharField(choices=[(b'text', 'Text'), (b'string', 'String'), (b'int', 'Integer'), (b'double', 'Double'), (b'file', 'File')], max_length=32, verbose_name='Type')),
                ('value', models.FileField(blank=True, max_length=5000, null=True, upload_to=b'', verbose_name='Value')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_settings', to='sites.Site', verbose_name='Site')),
            ],
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_protocol', models.CharField(choices=[(b'http://', 'HTTP'), (b'https://', 'HTTPS')], max_length=32, verbose_name='From Protocol')),
                ('from_domain', models.CharField(blank=True, max_length=256, null=True, verbose_name='From Domain')),
                ('from_url', models.CharField(max_length=2048, verbose_name='From URL')),
                ('to_protocol', models.CharField(choices=[(b'http://', 'HTTP'), (b'https://', 'HTTPS')], max_length=32, verbose_name='To Protocol')),
                ('to_domain', models.CharField(max_length=256, verbose_name='To Domain')),
                ('to_url', models.CharField(max_length=2048, verbose_name='To URL')),
                ('regex', models.BooleanField(default=False, verbose_name='RegEx')),
                ('public', models.BooleanField(default=True, verbose_name='Public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Redirect',
                'verbose_name_plural': 'Redirects',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=32, verbose_name='Language')),
                ('template', models.CharField(blank=True, max_length=128, null=True, verbose_name='Template')),
                ('robots', models.TextField(blank=True, null=True, verbose_name='robots.txt')),
                ('code_head', models.TextField(blank=True, null=True, verbose_name='Head Code')),
                ('code_footer', models.TextField(blank=True, null=True, verbose_name='Footer Code')),
                ('public', models.BooleanField(default=True, verbose_name='Public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='sites.Site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Sites Settings',
            },
        ),
        migrations.AlterUniqueTogether(
            name='data',
            unique_together=set([('site', 'url')]),
        ),
    ]
