# Generated by Django 4.1.3 on 2022-11-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitesettings", old_name="robots", new_name="robots_txt",
        ),
        migrations.AlterField(
            model_name="data",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="extrasettings",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="extrasettings",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("string", "String"),
                    ("int", "Integer"),
                    ("double", "Double"),
                    ("file", "File"),
                ],
                max_length=32,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="extrasettings",
            name="value",
            field=models.FileField(
                blank=True,
                max_length=5000,
                null=True,
                upload_to="",
                verbose_name="Value",
            ),
        ),
        migrations.AlterField(
            model_name="redirect",
            name="from_protocol",
            field=models.CharField(
                choices=[("http://", "HTTP"), ("https://", "HTTPS")],
                max_length=32,
                verbose_name="From Protocol",
            ),
        ),
        migrations.AlterField(
            model_name="redirect",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="redirect",
            name="to_protocol",
            field=models.CharField(
                choices=[("http://", "HTTP"), ("https://", "HTTPS")],
                max_length=32,
                verbose_name="To Protocol",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="template",
            field=models.CharField(
                blank=True,
                choices=[],
                max_length=128,
                null=True,
                verbose_name="Template",
            ),
        ),
    ]
