# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_auto_20160215_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='template',
            field=models.CharField(blank=True, choices=[(b'/home/lesha/Dropbox/implantatberlin.com/Code/apps/../templates/', b'templates')], max_length=128, null=True, verbose_name='Template'),
        ),
    ]
