# Generated by Django 4.1.3 on 2022-11-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0002_rename_robots_sitesettings_robots_txt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="data",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Meta data",
                "verbose_name_plural": "Meta data",
            },
        ),
        migrations.AlterModelOptions(
            name="sitesettings",
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Sites settings",
            },
        ),
        migrations.RemoveField(model_name="sitesettings", name="template",),
        migrations.AddField(
            model_name="sitesettings",
            name="sitemap_xml",
            field=models.TextField(blank=True, verbose_name="sitemap.xml"),
        ),
        migrations.AlterField(
            model_name="data",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="data",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="language",
            field=models.CharField(max_length=5, verbose_name="Language"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="robots_txt",
            field=models.TextField(blank=True, default="", verbose_name="robots.txt"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
