# Generated by Django 4.1.3 on 2022-11-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0003_alter_data_options_alter_sitesettings_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="robots_txt",
            field=models.TextField(blank=True, verbose_name="robots.txt"),
        ),
    ]
