# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_auto_20160301_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='template',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Template'),
        ),
    ]
