# Generated by Django 4.1.3 on 2022-11-21 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0004_alter_sitesettings_robots_txt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="data", old_name="head_code", new_name="head",
        ),
    ]
