# Generated by Django 4.1.3 on 2022-11-21 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0005_rename_head_code_data_head"),
    ]

    operations = [
        migrations.RenameField(
            model_name="data", old_name="footer_code", new_name="footer",
        ),
    ]
