# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0005_auto_20160310_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='code_footer',
            field=models.TextField(blank=True, null=True, verbose_name='Footer Code'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='code_head',
            field=models.TextField(blank=True, null=True, verbose_name='Head Code'),
        ),
    ]
