# Generated by Django 4.1.3 on 2022-11-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0007_alter_data_footer_alter_data_head"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitesettings", old_name="code_head", new_name="head",
        ),
    ]
