# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('seo', '0007_extrasettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='sites.Site', verbose_name='Site'),
        ),
        migrations.RemoveField(
            model_name='data',
            name='sites',
        ),
        migrations.AlterUniqueTogether(
            name='data',
            unique_together=set([('site', 'url')]),
        ),
    ]
