# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0008_auto_20160318_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='sites.Site', verbose_name='Site'),
        ),
    ]
