# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0009_auto_20160318_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='sites.Site', verbose_name='Site'),
        ),
    ]
